server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authModule
          uri: http://localhost:8762
          predicates:
            - Path=/api/v1/auth/**
        - id: userModule
          uri: http://localhost:8763
          predicates:
            - Path=/api/v1/user/**
        - id: invitationModule
          uri: http://localhost:8764
          predicates:
            - Path=/api/v1/invitation/**